name: Deployment
run-name: Deployment by @${{ github.actor }}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Build_and_Push_to_DockerHub:
    uses: ./.github/workflows/build_and_push_to_dockerhub.yml
    secrets: inherit
